//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmo_pd_db_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAZOWE_STATYSTYKI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAZOWE_STATYSTYKI()
        {
            this.KLASY_POSTACI = new HashSet<KLASY_POSTACI>();
            this.RASies = new HashSet<RASY>();
        }
    
        public decimal ID { get; set; }
        public decimal BASE_HP { get; set; }
        public decimal BASE_MP { get; set; }
        public decimal BASE_STR { get; set; }
        public decimal BASE_AG { get; set; }
        public decimal BASE_INT { get; set; }
        public decimal BASE_STAMINA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KLASY_POSTACI> KLASY_POSTACI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RASY> RASies { get; set; }
    }
}
