//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmo_pd_db_client
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MmoContext : DbContext
    {
        public MmoContext()
            : base("name=MmoContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAZOWE_STATYSTYKI> BAZOWE_STATYSTYKI { get; set; }
        public virtual DbSet<KLASY_POSTACI> KLASY_POSTACI { get; set; }
        public virtual DbSet<KONTA> KONTAs { get; set; }
        public virtual DbSet<MAPY> MAPies { get; set; }
        public virtual DbSet<POSTACIE> POSTACIEs { get; set; }
        public virtual DbSet<POZYCJE> POZYCJEs { get; set; }
        public virtual DbSet<RASY> RASies { get; set; }
        public virtual DbSet<STATYSTYKI> STATYSTYKIs { get; set; }
        public virtual DbSet<TYPY_UMIEJETNOSCI> TYPY_UMIEJETNOSCI { get; set; }
        public virtual DbSet<UMIEJETNOSCI> UMIEJETNOSCIs { get; set; }
        public virtual DbSet<UMIEJETNOSCI_POSTAC> UMIEJETNOSCI_POSTAC { get; set; }
        public virtual DbSet<WYGLAD> WYGLADs { get; set; }
        public virtual DbSet<GRACZE_NA_MAPACH> GRACZE_NA_MAPACH { get; set; }
        public virtual DbSet<POSTACIE_LEVEL_AVG> POSTACIE_LEVEL_AVG { get; set; }
        public virtual DbSet<POSTACIE_WYSOKOSC_MAPA> POSTACIE_WYSOKOSC_MAPA { get; set; }
    }
}
