//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmo_pd_db_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTACIE_LEVEL_AVG
    {
        public string EMAIL { get; set; }
        public string LOGIN { get; set; }
        public string NICKNAME { get; set; }
        public byte CH_LEVEL { get; set; }
    }
}
