//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmo_pd_db_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTACIE_WYSOKOSC_MAPA
    {
        public string NICKNAME { get; set; }
        public string NAZWA_MAPY { get; set; }
        public decimal WYSOKOSC_NA_MAPIE { get; set; }
    }
}
