//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmo_pd_db_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATYSTYKI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STATYSTYKI()
        {
            this.POSTACIEs = new HashSet<POSTACIE>();
        }
    
        public decimal ID { get; set; }
        public byte CH_LEVEL { get; set; }
        public decimal HP { get; set; }
        public decimal MANA { get; set; }
        public decimal STR { get; set; }
        public decimal AGILITY { get; set; }
        public decimal INTELIGENCE { get; set; }
        public decimal STAMINA { get; set; }
        public decimal EXP_POINTS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSTACIE> POSTACIEs { get; set; }
    }
}
