//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmo_pd_db_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPY_UMIEJETNOSCI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TYPY_UMIEJETNOSCI()
        {
            this.UMIEJETNOSCIs = new HashSet<UMIEJETNOSCI>();
        }
    
        public decimal ID { get; set; }
        public string TYPE_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UMIEJETNOSCI> UMIEJETNOSCIs { get; set; }
    }
}
