//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmo_pd_db_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMIEJETNOSCI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UMIEJETNOSCI()
        {
            this.UMIEJETNOSCI_POSTAC = new HashSet<UMIEJETNOSCI_POSTAC>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> SKILL_TYPE_ID { get; set; }
        public string SKILL_NAME { get; set; }
        public decimal BASE_DMG { get; set; }
    
        public virtual TYPY_UMIEJETNOSCI TYPY_UMIEJETNOSCI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UMIEJETNOSCI_POSTAC> UMIEJETNOSCI_POSTAC { get; set; }
    }
}
